### ISSUE TITLE
Occasional "object has been modified" error when syncing labels to nodes

### ISSUE THREAD

**Issue by mattkelly** [containership/cluster-manager#55]
#### What is the current behavior?

We see an occasional error when syncing cluster and node pool labels to nodes:

```
2019-04-05T15:23:45.745Z        ERROR   error syncing "49ba0a56-5f78-4869-9835-77e468669353": updating node with new labels: Operation cannot be fulfilled on nodes "49ba0a56-5f78-4869-9835-77e468669353": the object has been modified; please apply your changes to the latest version and try again. Has been resynced 5 times
```

This may be related to how often/aggressively we update nodes. We could instead only update nodes if something has actually changed. This would require more complex label syncing logic. 

#### What is the expected behavior?
No errors.

#### Additional Context
Labeling this as a bug. Optimization also seems appropriate, but bug makes sense to me.

### Reproduction
- Create some labels using csctl and watch for errors as they sync to the nodes

### Evidence
See above.

**Comment by nicktate** [comment]
Might be as simple as adding three lines to these files:

* https://github.com/containership/cluster-manager/blob/master/pkg/coordinator/node_pool_label_controller.go#L256
* https://github.com/containership/cluster-manager/blob/master/pkg/coordinator/cluster_label_controller.go#L245

pseudo-code:
```
if checkIfLabelsEquivalent(nodeLabels, node.Labels) {
  return nil
}
```
