### ISSUE TITLE
RBAC Roles and Bindings Sync Controller

### ISSUE THREAD

**Issue by nicktate** [containership/cluster-manager#63]
#### How would you like the feature to work?

* There are cloud `roles` and `rolebindings` that will need to be synced down to clusters. 
* A containership `role` has a list of `rules`, where each rule can be of type `cloud` or `kubernetes`. 
  * Will need to filter out only `kubernetes` related rules
  * Create a kubernetes `clusterrole` for every `role` with all of its corresponding rules
  * Use some `metadata.label` to keep track of synced `roles`
* The `rolebindings` may contain multiple `cluster_ids` that it pertains to
  * Sync will need to filter only bindings pertaining to current cluster
  * a `clusterolebinding` or `rolebinding` will need to be created on the cluster depending on if a `namespace` scope is present

#### Additional Context
* Need to fill in full details of schema @mikestoltz . This is a best effort regurgitation of our high level discussion from last week

**Comment by normanjoyner** [comment]
We should also block this until we’ve decided if vanilla RBAC is preferred over OPA.

**Comment by mattkelly** [comment]
Let's repoint this after the above question is answered.
