### ISSUE TITLE
"All namespaces" (cluster) role binding is getting applied as a rolebinding to multiple namespaces instead of a clusterrolebinding

### ISSUE THREAD

**Issue by mikestoltz** [containership/cluster-manager#77]
#### What is the current behavior?
Some cluster role bindings are also being applied as individual namespace role bindings

#### What is the expected behavior?
Cluster role bindings should only be applied as cluster role bindings

#### Additional Context
The cluster I was seeing this on has been deleted, but it was happening fairly often and should be reproducible.

**Comment by normanjoyner** [comment]
We need logs / a reproducible environment or steps in order to investigate this further.

**Comment by mattkelly** [comment]
@mikestoltz please re-open if this is able to reproduced. Closing for now.
